### ISSUE TITLE
Tick format for dates before 1900-01-01 rendered as ":00"

### ISSUE THREAD

**Issue by SebastianSkoog** [d3/d3-time#30] opened 2018-08-08 12:04 UTC
Default tickFormat causes dates before 1900-01-01 incorrectly rendered as ":00".
Example: https://jsfiddle.net/x50gop7k/7/

**Comment by mbostock** [comment] 2018-08-08 13:56
Duplicate of #29.

**Closed by mbostock** 2018-08-08 13:56 UTC
